CREATE TABLE IF NOT EXISTS Artists (
    ArtistID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Songs (
    SongID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    ArtistID INTEGER,
    FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID)
);
